ecommerce_web/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homecommon/',include('homecommon.urls')),
    path('ecommerce_admin/',include('ecommerce_admin.urls')),
    path('seller/',include('seller.urls')),
    path('customer/',include('customer.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path 
from.import views
app_name='seller'

urlpatterns=[
   path('sel_home/',views.sel_home,name='sel_home'),
   path('product_catelogue/',views.product_catelogue,name='product_catelogue'),
   path('add_product/',views.add_product,name='add_product'),
   path('change_pass/',views.change_pass,name='change_pass'),
   path('sel_profile/',views.sel_profile,name='sel_profile'),
   path('sel_home/',views.sel_home,name='sel_home'),
   path('recent_orders/',views.recent_orders,name='recent_orders'),
   path('update_stock/',views.update_stock,name='update_stock'),
   path('order_his/',views.order_his,name='order_his'),
]

seller/models.py
from django.db import models

from homecommon.models import Seller



# Create your models here.
class Product(models.Model):
    seller=models.ForeignKey(Seller,on_delete=models.CASCADE)
    product_name=models.CharField(max_length=50)
    product_num=models.CharField(max_length=20)
    description=models.CharField(max_length=500)
    product_stock=models.BigIntegerField()
    Product_price=models.FloatField()
    image=models.ImageField(upload_to='product/')

seller/views.py
from django.shortcuts import render
from django.http import HttpResponse

from homecommon.models import Seller
from seller import models
from seller.models import Product




# Create your views here.

def product_catelogue(request):
    product_details=Product.objects.filter(seller_id=request.session['seller'])
    return render(request,'sel_templates/product_catelogue.html',{'data':product_details})

def add_product(request):
    if request.method=='POST':
        # pseller=request.POST['']
        pname=request.POST['s_pname']
        pnum=request.POST['s_pid']
        pdescription=request.POST['s_pdescription']
        pstock=request.POST['s_pstock'] 
        pprice=request.POST['s_pprice']
        pimg=request.FILES['s_pimg']
        new_product=Product(
            seller_id= request.session['seller'],
            product_name= pname,
            product_num=pnum,
            description=pdescription,
            product_stock= pstock,
            Product_price=pprice,
            image= pimg,   
        )
       
        new_product.save()
    return render(request,'sel_templates/add_product.html')

def change_pass(request):
    return render(request,'sel_templates/change_pass.html')

def sel_profile(request):
    seller_details = Seller.objects.get(id = request.session['seller'])
    return render(request,'sel_templates/sel_profile.html',{'data':seller_details})

def sel_home(request):

    seller_data=Seller.objects.get(id=request.session['seller'])
    return render(request,'sel_templates/sel_home.html',{'data':seller_data})

def recent_orders(request):
    return render(request,'sel_templates/recent_orders.html')

def update_stock(request):
    return render(request,'sel_templates/update_stock.html')

def order_his(request):
    return render(request,'sel_templates/order_his.html')

seller/templates/sel_templates/add_product.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="main_div">
            <div class="page_div">
                <!-- <div class="amazon_div">
                    <h1>AMAZON.IN</h1>
                </div> -->
                <div class="content_div">
                    <div class="create_div">
                        <div class="menu_div">
                            <h2>MENU</h2>
                        </div>
                        <div><a href="{% url 'seller:sel_home' %}"> <label id="alllabel">Home</label></a> </div>
                        <div><a href="{% url 'seller:product_catelogue' %}"> <label id="alllabel">Product
                                    Catelogue</label></a></div>
                        <div><a href="{% url 'seller:add_product' %}"> <label id="alllabel">Add Product</label></a>
                        </div>
                        <div><a href="{% url 'seller:change_pass' %}"> <label id="alllabel">Change Password</label></a>
                        </div>
                        <div><a href="{% url 'seller:sel_profile' %}"> <label id="alllabel">Profile</label></a> </div>
                        <div><a href="{% url 'seller:recent_orders' %}"> <label id="alllabel">Recent Orders</label></a>
                        </div>
                        <div><a href="{% url 'seller:update_stock' %}"> <label id="alllabel">Update Stock</label></a>
                        </div>
                        <div><a href="{% url 'seller:order_his' %}"> <label id="alllabel">Order History</label></a>
                        </div>
                        <div>
                            <h1>PRODUCT DETAILS</h1>
                        </div>
                        <table>

                            <tr>
                                <td><label for="">Product Name</label></td>
                            </tr>
                            <tr>
                                <td><input type="text" placeholder="" name="s_pname"></td>
                            </tr>
                            <tr>
                                <td><label for="">Product num</label></td>

                            </tr>
                            <tr>
                                <td><input type="text" name="s_pid"></td>
                            <tr>
                                <td><label for="">Description</label></td>
                            </tr>
                            <tr>
                                <td><input type="text" placeholder="" name="s_pdescription" id=""></td>
                            </tr>

                            <tr>
                                <td><label for="">Product Stock</label></td>
                            </tr>
                            <tr>
                                <td><input type="text" placeholder="" name="s_pstock"></td>
                            </tr>


                            <tr>
                                <td><label for="">Product price</label></td>
                            </tr>
                            <tr>
                                <td><input type="text" name="s_pprice"></td>
                            </tr>
                            <tr>
                                <td><label for="myfile">Product image</label>
                                </td>
                            </tr>
                            <tr>
                                <td><input type="file" id="myfile" name="s_pimg"><br><br></td>
                            </tr>
                            <tr>

                                <td><input type="submit" name="" value="submit"></td>
                            </tr>


                        </table>
                    </div>

                </div>

            </div>

        </div>
    </form>
</body>

</html>

seller/templates/sel_templates/order_his.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

seller/templates/sel_templates/product_catelogue.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .container{
            width: 100px;
            height: 200px;

        }
        .card-img-top{
            width: 70px;
            height: 70px;

        }
        .product{
            display: grid;
            grid-template-columns: auto auto auto auto;
        }
    </style>
</head>

<body>
    <form action="" method="POST" enctype="multipart/form-data">
        <div class="container">
            <div class="seller">
                <h1>PRODUCT CATELOGUE</h1>
            </div>
            <div class="product">
                {% for product in data %}

            <div class="card" style="width: 18rem;">
                <img src="{{product.image.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{product_details.product_name}}</h5>
                    <p class="card-text">{{product.Product_price}}</p>
                    <p class="card-text">{{product.description}}</p>
                    <input type="button" value="update stock"><a href="#" class="btn btn-primary"></a>
                </div>
            </div>
            
                {% endfor %}
            </div>
            
        </div>
    </form>
</body>

</html>

seller/templates/sel_templates/recent_orders.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

seller/templates/sel_templates/sel_home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <form action="">
        <div class="main_div">
            <div class="page_div">
                <div class="welcom">
                    <h1> WELCOME {{data.seller_name}}</h1>
                </div>
                <div class="content_div">
                    <div class="menu_div">
                        <h2>MENU</h2>
                    </div>
                    <div><a href="{% url 'seller:sel_home' %}"> <label id="alllabel">Home</label></a> </div>
                    <div><a href="{% url 'seller:product_catelogue' %}"> <label id="alllabel">Product
                                Catelogue</label></a></div>
                    <div><a href="{% url 'seller:add_product' %}"> <label id="alllabel">Add Product</label></a> </div>
                    <div><a href="{% url 'seller:change_pass' %}"> <label id="alllabel">Change Password</label></a>
                    </div>
                    <div><a href="{% url 'seller:sel_profile' %}"> <label id="alllabel">Profile</label></a> </div>
                    <div><a href="{% url 'seller:recent_orders' %}"> <label id="alllabel">Recent Orders</label></a>
                    </div>
                    <div><a href="{% url 'seller:update_stock' %}"> <label id="alllabel">Update Stock</label></a> </div>
                    <div><a href="{% url 'seller:order_his' %}"> <label id="alllabel">Order History</label></a></div>



                </div>
            </div>
        </div>
    </form>
</body>

</html>

seller/templates/sel_templates/sel_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   <form action=""method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <tr>
        <h1>SELLER PROFILE</h1>
        name :
        <h1>{{data.seller_name}}</h1>
        image :
        <img src="{{data.company_logo.url}}" alt="">
        <br>
        company name:{{data.company_name}}<br>
        account number:{{data.s_acc_no}}<br>

        IFSC CODE:{{data.ifsc}}<br>
        BRANCH:{{data.s_branch_name}}<br>
        ACCOUNT HOLDER NAME:{{data.acc_name}}<br>
        PHONE NUMBER:{{data.mobile}} <br>
        E-MAIL:{{data.e_mail}} <br>
        ADDRESS:{{data.address}} <br>
        USERNAME:{{data.Username}} <br>
    </tr>
   </form>
    
</body>
</html>

seller/templates/sel_templates/update_stock.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <form action="">
        <div class="main_div">
            <div class="page_div">
                <!-- <div class="amazon_div">
                    <h1>AMAZON.IN</h1>
                </div> -->
                <div class="content_div">
                    <div class="create_div">
                        <div class="menu_div">
                            <h2>MENU</h2>
                        </div>
                        <div><a href="{% url 'seller:sel_home' %}"> <label id="alllabel">Home</label></a> </div>
                        <div><a href="{% url 'seller:product_catelogue' %}"> <label id="alllabel">Product
                                    Catelogue</label></a></div>
                        <div><a href="{% url 'seller:add_product' %}"> <label id="alllabel">Add Product</label></a>
                        </div>
                        <div><a href="{% url 'seller:change_pass' %}"> <label id="alllabel">Change Password</label></a>
                        </div>
                        <div><a href="{% url 'seller:sel_profile' %}"> <label id="alllabel">Profile</label></a> </div>
                        <div><a href="{% url 'seller:recent_orders' %}"> <label id="alllabel">Recent Orders</label></a>
                        </div>
                        <div><a href="{% url 'seller:update_stock' %}"> <label id="alllabel">Update Stock</label></a>
                        </div>
                        <div><a href="{% url 'seller:order_his' %}"> <label id="alllabel">Order History</label></a>
                        </div>
                        <table>
                            <tr>
                                <td>product</td>
                                <td>Current stock</td>
                                <td>New Stock</td>
                            </tr>
                            <tr>
                                <td><input type="select" name="select product" id=""></td>
                                <td><input type="text" name="" id=""></td>
                                <td><input type="text"></td>
                            </tr>
                            <tr><td><button>Submit</button></td></tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </form>
</body>

</html>