customer/urls.py
from django.urls import path 
from.import views
app_name='customer'

urlpatterns=[
   path('cus_home/',views.cus_home,name='cus_home'),
   path('product_detail/',views.product_detail,name='product_detail'),
   path('myorder/',views.myorder,name='myorder'),
   path('cus_profile/',views.cus_profile,name='cus_profile'),
   path('mycart/',views.mycart,name='mycart'),
   path('change_pass/',views.change_pass,name='change_pass'),
   path('logout/',views.logout,name='logout'),

]

ecommerce_web/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homecommon/',include('homecommon.urls')),
    path('ecommerce_admin/',include('ecommerce_admin.urls')),
    path('seller/',include('seller.urls')),
    path('customer/',include('customer.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homecommon/urls.py
from django.urls import path
from .import views
app_name='homecommon'

urlpatterns=[
   path('customer_login/',views.customer_login,name='customer_login'),
   path('customer_registration/',views.customer_registration,name='customer_registration'),
   path('home/',views.home,name='home'),
   path('seller_login/',views.seller_login,name='seller_login'),
   path('seller_reg/',views.seller_reg,name='seller_reg'),
]

seller/urls.py
from django.urls import path 
from.import views
app_name='seller'

urlpatterns=[
   path('sel_home/',views.sel_home,name='sel_home'),
   path('product_catelogue/',views.product_catelogue,name='product_catelogue'),
   path('add_product/',views.add_product,name='add_product'),
   path('change_pass/',views.change_pass,name='change_pass'),
   path('sel_profile/',views.sel_profile,name='sel_profile'),
   path('sel_home/',views.sel_home,name='sel_home'),
   path('recent_orders/',views.recent_orders,name='recent_orders'),
   path('update_stock/',views.update_stock,name='update_stock'),
   path('order_his/',views.order_his,name='order_his'),
]

customer/models.py
from django.db import models

from homecommon.models import Customer
from seller.models import Product

# Create your models here.
# ADD TO CART
# PRODUCT 
# CUSTOMER 
# QUTY (INT OR BIGINT)
class Mycart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    customer=models.ForeignKey(Customer,on_delete=models.CASCADE)
    quantity=models.BigIntegerField()
    

customer/views.py
from itertools import product
from django.shortcuts import render,redirect
from django.http import HttpResponse
from customer.models import Mycart
from homecommon.models import Customer

from seller.models import Product

# Create your views here.
def cus_home(request):
    prod_list=Product.objects.all()
    return render(request,'cus_templates/cus_home.html',{'prod_data':prod_list})


def product_detail(request):
    return render(request,'cus_templates/product_detail.html')

def mycart(request):  
    if request.method=='POST':
          
        qty=request.POST['m_qty']
        new_cart=Mycart(
            # product_id= request.session['product'],
            # customer_id=request.session['customer'],
            quantity=qty,
          )
        new_cart.save()
    
    return render(request,'cus_templates/mycart.html')

def myorder(request):
    return render(request,'cus_templates/myorder.html')

def change_pass(request):
    return render(request,'cus_templates/change_pass.html')

def cus_profile(request):
    customer_details = Customer.objects.get(id = request.session['customer'])
    return render(request,'cus_templates/cus_profile.html',{'data':customer_details})

def logout(request):
    del request.session['customer']
    request.session.flush()
    return redirect('homecommon:home')
    

customer/templates/cus_templates/cus_home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<style>
    /* .container {
        width: 100px;
        height: 200px;

    } */

    .card-img-top {
        width: 70px;
        height: 70px;

    }

    .product {
        display: grid;
        grid-template-columns: auto auto auto auto;
    }
</style>

<body>
    <form action="" method="POST" enctype="multipart/form-data">

        <div class="main_div">
            <div class="page_div">
                <div class="amazon_div">
                    <h1>CUSTOMER HOME</h1>



                    <table>
                        <tr>
                            <!-- <tr><td>  <a href="{% url 'customer:cus_home' %}"><input type="button" value="Home"></a></td> -->
                            <td> <a href="{% url 'customer:product_detail' %}"><input type="button"
                                        value="Products"></a>
                            </td>
                            <td> <a href="{% url 'customer:myorder' %}"><input type="button" value="Orders"></a></td>
                            <td> <a href="{% url 'customer:change_pass' %}"><input type="button"
                                        value="Change Password"></a></td>
                            <td> <a href="{% url 'customer:mycart' %}"><input type="button" value="my cart"></a></td>
                            <td> <a href="{% url 'customer:cus_profile' %}"><input type="button" value="Profile"></a>
                            </td>
                            <td> <a href="{% url 'homecommon:home' %}"><input type="button" value="Log out"></a></td>
                        </tr>
                    </table>
                </div>
                <div class="product">
                    {% for product in prod_data %}

                    <div class="card" style="width: 18rem;">
                        <img src="{{product.image.url}}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{product_details.product_name}}</h5>
                            <p class="card-text">{{product.Product_price}}</p>
                            <p class="card-text">{{product.description}}</p>
                            <input type="button" value="update stock"><a href="#" class="btn btn-primary"></a>
                        </div>
                    </div>

                    {% endfor %}
                </div>


            </div>
        </div>
        </div>

    </form>

</body>

</html>

customer/templates/cus_templates/cus_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <tr>
            <h1>CUSTOMER PROFILE</h1>
            name :
            <h1>{{data.customer_name}}</h1>
            
            <img src="{{data.image.url}}" alt="">
            <br>
            GENDER:{{data.gender}}<br>
            PHONE NUMBER:{{data.ph_number}<br>
            E-MAIL:{{data.e_mail}}<br>
            ADDRESS:{{data.address}}<br>
            
        </tr>
       </form>
        
</body>
</html>

customer/templates/cus_templates/mycart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container">
            <div class="tablediv">
                <table>
                    <tr>
                        <td>slno</td>
                    
                        <td>p_image</td>
                    
                    
                        <td>name</td>
                    
                    
                        <td>price</td>
                    
                    
                        <td>quantity</td>
                    
                    
                        <td>total</td>
                    </tr>
                    <tr>
                        <td><input type="text" name="m_slno"></td>
                        <td><input type="text"name="m_image"></td>
                        <td><input type="text" name="m_name" id=""></td>
                        <td><input type="text" name="m_price" id=""></td>
                        <td> <select name="quantity" name="m_qty">
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                          </select></td>
                        <td><input type="text" name="m_total" id=""></td>
                    </tr>
                    <tr>

                        <td><input type="button" value="CheckOut"></td>
                    </tr>
                    
                </table>

            </div>

        </div>

    </form>
    
</body>
</html>

customer/templates/cus_templates/product_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    product_detail
</body>
</html>