ecommerce_admin/urls.py
from django.urls import path 
from.import views
app_name='ecommerce_admin'

urlpatterns=[
   path('ad_login/',views.ad_login,name='ad_login'),
   path('approve_seller/',views.approve_seller,name='approve_seller'),
   path('view_seller/',views.view_seller,name='view_seller'),
   path('admin_home/',views.admin_home,name='admin_home'),

]

ecommerce_web/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homecommon/',include('homecommon.urls')),
    path('ecommerce_admin/',include('ecommerce_admin.urls')),
    path('seller/',include('seller.urls')),
    path('customer/',include('customer.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path 
from.import views
app_name='seller'

urlpatterns=[
   path('sel_home/',views.sel_home,name='sel_home'),
   path('product_catelogue/',views.product_catelogue,name='product_catelogue'),
   path('add_product/',views.add_product,name='add_product'),
   path('change_pass/',views.change_pass,name='change_pass'),
   path('sel_profile/',views.sel_profile,name='sel_profile'),
   path('sel_home/',views.sel_home,name='sel_home'),
   path('recent_orders/',views.recent_orders,name='recent_orders'),
   path('update_stock/',views.update_stock,name='update_stock'),
   path('order_his/',views.order_his,name='order_his'),
]

ecommerce_admin/models.py
from django.db import models

# Create your models here.

ecommerce_admin/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def ad_login(request):
    return render(request,'admin_templates/ad_login.html')



def approve_seller(request):
    return render(request,'admin_templates/approve_seller.html')

def view_seller(request):
    return render(request,'admin_templates/view_seller.html')

def admin_home(request):
    return render(request,'admin_templates/admin_home.html')

ecommerce_admin/templates/admin_templates/ad_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="main_div">
        <div class="">ADMIN LOGIN</div>

    </div>
</body>
</html>

ecommerce_admin/templates/admin_templates/admin_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="">
        <h1>ADMIN PANEL</h1>
       <a href="{% url 'ecommerce_admin:approve_seller' %}"><button> Approve seller</button> </a>
       <a href="{% url 'ecommerce_admin:view_seller' %}"><button> view seller</button> </a>
       <a href="#"><button> view customer</button> </a>
       <table>
        <TR><td>APPROVE SELLER</td></TR>
        <tr>
            <td>sno</td>
            <td>Name</td>
            <td>Email</td>
            <td>Acc no</td>
            <td>IFSC</td>
            <td>Branch</td>
            <td>Company NAme</td>
            <td>Phone</td>
            <td>seller pic</td>
            <td>Actions</td>
        </tr>
       </table>


    </form>
    
</body>
</html>

ecommerce_admin/templates/admin_templates/approve_seller.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="">
        <h1>ADMIN PANEL</h1>
       <a href="{% url 'ecommerce_admin:approve_seller' %}"><button> Approve seller</button> </a>
       <a href="{% url 'ecommerce_admin:view_seller' %}"><button> view seller</button> </a>
       <a href="#"><button> view customer</button> </a>
       <table>
        <TR><td>APPROVE SELLER</td></TR>
        <tr>
            <td>sno</td>
            <td>Name</td>
            <td>Email</td>
            <td>Acc no</td>
            <td>IFSC</td>
            <td>Branch</td>
            <td>Company NAme</td>
            <td>Phone</td>
            <td>seller pic</td>
            <td>Actions</td>
        </tr>
       </table>


    </form>
    
</body>
</html>

ecommerce_admin/templates/admin_templates/view_seller.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="">
        <h1>ADMIN PANEL</h1>
       <a href="{% url 'ecommerce_admin:approve_seller' %}"><button> Approve seller</button> </a>
       <a href="{% url 'ecommerce_admin:view_seller' %}"><button> view seller</button> </a>
       <a href="#"><button> view customer</button> </a>
       <table>
        <TR><td>view SELLER</td></TR>
        <tr>
            <td>sno</td>
            <td>Name</td>
            <td>Email</td>
            <td>Acc no</td>
            <td>IFSC</td>
            <td>Branch</td>
            <td>Company NAme</td>
            <td>Phone</td>
            <td>seller pic</td>
            <td>Actions</td>
        </tr>
       </table>


    </form>
    
</body>
</html>